package uz.shox.med.enums;

public enum NotificationType {
    APPOINTMENT_CREATED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    LAB_RESULT_READY,
    MARKETING,
    SYSTEM
}